# script arguments
dataset_name: argilla/FinePersonas-v0.1
logging_level: DEBUG
cache_dir: .cache
topic: math

# model config
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
model_revision: main
# torch_dtype: bfloat16
# attn_implementation: flash_attention_2
